# Cloudflare Tunnel 配置

tunnel: 215fcc07-11ca-49ae-82cc-3c3b3ad27e18
credentials-file: /etc/cloudflared/certs/215fcc07-11ca-49ae-82cc-3c3b3ad27e18.json
protocol: http2

ingress:
  - hostname: api.chronono.org
    service: http://host.docker.internal:8000
  - hostname: web.chronono.org
    service: http://host.docker.internal:3000
  - service: http_status:404
